websites:
  - https://www.chase.com
  - https://www.jpmorgan.com
  - https://www.google.com
  - https://www.amazon.com
  - https://www.microsoft.com

timeout_seconds: 5
refresh_interval_seconds: 30
max_history_length: 15
